[package]
name = "wall_runner_levels"
version = "0.2.0"
edition = "2021"

[dependencies]
wall_runner_utils = { path = "../wall_runner_utils" }
bevy = "0.7.0"
bevy_rapier3d = "0.14.1"
bevy_atmosphere = "0.3.1"
