name: unit-test

on:
  pull_request:
  push:
    branches:
      - master

env:
  NIGHTLY_TOOLCHAIN: nightly-2022-07-13

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all
